variables:
    SolutionBaseName: 'DFC.Notify'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: BuildTestAndAnalyze
    pool:
      name: NCS - CI and CD
      demands:
      - msbuild
      - visualstudio
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        DotNetCoreVersion: 3.1.101
        PublishWebApp: true
        TestSuffix: UnitTests

    - task: NuGetCommand@2
      displayName: "Pack and version Notify280 nuget file"
      inputs:      
        command: pack
        packagesToPack: 'Notify280/DFC.Notify280.csproj.nuspec' # Required when command == Pack
        packDestination: '$(System.DefaultWorkingDirectory)/Notify2.8.0' # Optional
        versioningScheme: byEnvVar
        versionEnvVar: GitVersion.MajorMinorPatch
        basePath: 'Notify280'

    - task: PublishPipelineArtifact@1
      displayName: Publish Notify280
      inputs:
        targetPath: "$(System.DefaultWorkingDirectory)/Notify2.8.0"
        artifactName: ${{ variables.SolutionBaseName }}.Notify280

    - task: NuGetCommand@2
      displayName: "Pack and version Notify290 nuget file"
      inputs:      
        command: pack
        packagesToPack: 'Notify290/DFC.Notify290.csproj.nuspec' # Required when command == Pack
        packDestination: '$(System.DefaultWorkingDirectory)/Notify2.9.0' # Optional
        versioningScheme: byEnvVar
        versionEnvVar: GitVersion.MajorMinorPatch
        basePath: 'Notify290'

    - task: PublishPipelineArtifact@1
      displayName: Publish Notify290
      inputs:
        targetPath: "$(System.DefaultWorkingDirectory)/Notify2.9.0"
        artifactName: ${{ variables.SolutionBaseName }}.Notify290